// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK1p56VGv_e01txhKQH2Hby9G2RQe7lR4',
    appId: '1:131334385712:web:ea30d265235aace0963df5',
    messagingSenderId: '131334385712',
    projectId: 'we-s-volleyball-manager',
    authDomain: 'we-s-volleyball-manager.firebaseapp.com',
    storageBucket: 'we-s-volleyball-manager.firebasestorage.app',
    measurementId: 'G-WY3QSPKXHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ujG6YjjvVdp_KZ1I8AIsK2KBRmdNJWw',
    appId: '1:131334385712:android:702e0d5add17c550963df5',
    messagingSenderId: '131334385712',
    projectId: 'we-s-volleyball-manager',
    storageBucket: 'we-s-volleyball-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2N-urfluerz3JarlmCkHw1dmVtPsxMmA',
    appId: '1:131334385712:ios:e5fcbc933db1998b963df5',
    messagingSenderId: '131334385712',
    projectId: 'we-s-volleyball-manager',
    storageBucket: 'we-s-volleyball-manager.firebasestorage.app',
    iosBundleId: 'com.example.volleyballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2N-urfluerz3JarlmCkHw1dmVtPsxMmA',
    appId: '1:131334385712:ios:e5fcbc933db1998b963df5',
    messagingSenderId: '131334385712',
    projectId: 'we-s-volleyball-manager',
    storageBucket: 'we-s-volleyball-manager.firebasestorage.app',
    iosBundleId: 'com.example.volleyballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK1p56VGv_e01txhKQH2Hby9G2RQe7lR4',
    appId: '1:131334385712:web:60e10783c3e4058c963df5',
    messagingSenderId: '131334385712',
    projectId: 'we-s-volleyball-manager',
    authDomain: 'we-s-volleyball-manager.firebaseapp.com',
    storageBucket: 'we-s-volleyball-manager.firebasestorage.app',
    measurementId: 'G-K9HGVK5D5B',
  );
}
